#!/bin/bash
# Publish entry point, run on the Jenkins agent by the "Publish" stage
# (see Jenkinsfile: gated on PUBLISH && !INSPECT_SCHEMA && !TEST_MODE, inside sshagent).
#
# Unlike the other scripts/*.sh (which exec INSIDE the container), this one runs on the
# agent HOST: the build artifacts already sit in ./target after the "Build indexes + DwCA"
# stage, and we ship them to the LA download hosts with rsync/ssh using the SSH key that the
# `sshagent` block loaded into the agent.
#
# What it does:
#   1. sha1sum the deliverables         -> target/SHA1SUMS-<release>.txt
#   2. rsync the .tgz to <others>/ and the DwCA .zip to <namedata>/ on the publish host
#   3. create the historical `nameindex-*` aliases as server-side symlinks (same sha1, so a
#      single checksum works for either name; avoids re-transmitting multi-GB files)
#   4. optionally mirror all of the above to the demo host
#   5. emit a ready-to-paste inventory fragment for la-toolkit's gbif-es-local-extras.ini
#      -> target/inventory-snippet-<release>.ini
#
# Naming (matches what gbif-taxonomy-for-la writes, <rd> = release):
#   namematching-gbif-backbone-lucene-8-<rd>.tgz   (Lucene 8, namematching-service)
#   namematching-gbif-backbone-lucene-6-<rd>.tgz   (Lucene 6, BIE + sensitive-data; optional)
#   gbif-backbone-<rd>.zip                          (DwCA "backbone total" for bie-index; optional)
#
# Required env (from the Jenkinsfile params): PUBLISH_HOST PUBLISH_USER
#   PUBLISH_OTHERS_PATH PUBLISH_NAMEDATA_PATH PUBLISH_URL_BASE
# Optional env: PUBLISH_DEMO(=true) DEMO_HOST DEMO_OTHERS_PATH DEMO_NAMEDATA_PATH
set -euo pipefail

RELEASE="${1:?usage: publish.sh <release-suffix>}"
cd "$(dirname "$0")/.."
TARGET="target"

# --- required config -------------------------------------------------------
: "${PUBLISH_HOST:?set PUBLISH_HOST (e.g. datos.gbif.es)}"
: "${PUBLISH_USER:?set PUBLISH_USER (ssh user on the publish host)}"
: "${PUBLISH_OTHERS_PATH:?set PUBLISH_OTHERS_PATH (docroot served at /others)}"
: "${PUBLISH_NAMEDATA_PATH:?set PUBLISH_NAMEDATA_PATH (docroot served at /namedata)}"
PUBLISH_URL_BASE="${PUBLISH_URL_BASE:-https://${PUBLISH_HOST}}"

SSH_OPTS="-o StrictHostKeyChecking=accept-new -o BatchMode=yes"

# --- resolve deliverables (publish only what the build actually produced) ---
L8="namematching-gbif-backbone-lucene-8-${RELEASE}.tgz"
L6="namematching-gbif-backbone-lucene-6-${RELEASE}.tgz"
DWCA="gbif-backbone-${RELEASE}.zip"

others_files=()
[[ -f "$TARGET/$L8" ]] && others_files+=("$L8")
[[ -f "$TARGET/$L6" ]] && others_files+=("$L6")
[[ -f "$TARGET/$DWCA" ]] || DWCA=""   # DwCA optional (BUILD_DWCA)

if [[ ${#others_files[@]} -eq 0 && -z "$DWCA" ]]; then
  echo "ERROR: no deliverables found in $TARGET for release '$RELEASE'"; exit 1
fi

# --- 1) checksums ----------------------------------------------------------
SHA_FILE="$TARGET/SHA1SUMS-${RELEASE}.txt"
( cd "$TARGET" && sha1sum "${others_files[@]}" ${DWCA:+"$DWCA"} ) > "$SHA_FILE"
echo "Checksums:"; cat "$SHA_FILE"

sha1_of() { awk -v f="$1" '$2==f {print $1}' "$SHA_FILE"; }
SHA_L8="$( [[ -f "$TARGET/$L8" ]] && sha1_of "$L8" || true )"
SHA_L6="$( [[ -f "$TARGET/$L6" ]] && sha1_of "$L6" || true )"
SHA_DWCA="$( [[ -n "$DWCA" ]] && sha1_of "$DWCA" || true )"

# --- rsync + alias helper (run once per target host) -----------------------
publish_to() {
  local host="$1" user="$2" others="$3" namedata="$4"
  echo "== Publishing to ${user}@${host} (others=$others, namedata=$namedata) =="

  if [[ ${#others_files[@]} -gt 0 ]]; then
    rsync -av --partial --progress -e "ssh $SSH_OPTS" \
      "${others_files[@]/#/$TARGET/}" "${user}@${host}:${others}/"
    # Historical `nameindex-*` aliases (same content -> same sha1) as server-side symlinks.
    for f in "${others_files[@]}"; do
      ssh $SSH_OPTS "${user}@${host}" \
        "cd '$others' && ln -sf '$f' '${f/namematching-/nameindex-}'"
    done
  fi

  if [[ -n "$DWCA" ]]; then
    rsync -av --partial --progress -e "ssh $SSH_OPTS" \
      "$TARGET/$DWCA" "${user}@${host}:${namedata}/"
  fi
}

# --- 2/3) primary host -----------------------------------------------------
publish_to "$PUBLISH_HOST" "$PUBLISH_USER" "$PUBLISH_OTHERS_PATH" "$PUBLISH_NAMEDATA_PATH"

# --- 4) optional demo mirror ----------------------------------------------
if [[ "${PUBLISH_DEMO:-false}" == "true" ]]; then
  : "${DEMO_HOST:?set DEMO_HOST when PUBLISH_DEMO=true}"
  publish_to "$DEMO_HOST" "${DEMO_USER:-$PUBLISH_USER}" \
    "${DEMO_OTHERS_PATH:-$PUBLISH_OTHERS_PATH}" \
    "${DEMO_NAMEDATA_PATH:-$PUBLISH_NAMEDATA_PATH}"
fi

# --- 5) inventory snippet for gbif-es-local-extras.ini ---------------------
SNIPPET="$TARGET/inventory-snippet-${RELEASE}.ini"
{
  echo "# Generated by scripts/publish.sh for release '${RELEASE}'."
  echo "# Paste into la-toolkit gbif-es-local-extras.ini (URLs use the nameindex-* aliases)."
  echo "# nameindex_to_use = custom"
  if [[ -n "$SHA_L6" ]]; then
    echo "custom_namematching_url             = ${PUBLISH_URL_BASE}/others/nameindex-gbif-backbone-lucene-6-${RELEASE}.tgz"
    echo "nameindex_datestamp                 = gbif-backbone-lucene-6-${RELEASE}"
    echo "nameindex_checksum                  = sha1:${SHA_L6}"
    echo "ala_sensitive_data_service_namematching_source = ${PUBLISH_URL_BASE}/others/nameindex-gbif-backbone-lucene-6-${RELEASE}.tgz"
    echo "ala_sensitive_data_service_namematching_sha1   = ${SHA_L6}"
  fi
  if [[ -n "$SHA_L8" ]]; then
    echo "ala_namemaching_service_source      = ${PUBLISH_URL_BASE}/others/nameindex-gbif-backbone-lucene-8-${RELEASE}.tgz"
    echo "ala_namemaching_service_source_sha1 = ${SHA_L8}"
  fi
  if [[ -n "$SHA_DWCA" ]]; then
    echo "custom_namedata_repo                = ${PUBLISH_URL_BASE}/namedata"
    echo "custom_name_sources                 = [{ \"name\": \"gbif-backbone\", \"checksum\": \"sha1:${SHA_DWCA}\", \"datestamp\": \"${RELEASE}\" }]"
  fi
} > "$SNIPPET"

echo "Inventory snippet written to $SNIPPET:"; echo; cat "$SNIPPET"
